# https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Call R-CMD-check

jobs:
  call-workflow-passing-data:
    uses: 2DegreesInvesting/tiltDevTools/.github/workflows/reusable-R-CMD-check.yaml@main
    secrets: inherit
